### ISSUE TITLE
Error: loading failed

### ISSUE THREAD

**Issue by vnijs** [thomasp85/MSGFgui#30]
Wanted to take a look at MSGFgui but ran into some trouble during install of MSGFplus. See below. I installed the latest Java runtime but get the same error.

> install_github('MSGFplus', 'thomasp85')
Downloading github repo thomasp85/MSGFplus@master
Installing MSGFplus
'/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD INSTALL  \
  '/private/var/folders/n4/rlnqcs4101b9m602tytx0kbc0000gn/T/RtmpwIvewh/devtools23e51698cc9/thomasp85-MSGFplus-bb3a656'  \
  --library='/Users/vnijs/Library/R/3.1/library' --install-tests 

* installing *source* package ‘MSGFplus’ ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Warning: running command ''java' -version 2>&1' had status 1
Error : .onLoad failed in loadNamespace() for 'MSGFplus', details:
  call: if (as.numeric(sub(".*\"\\d\\.(\\d).*", "\\1", javaVersion)) < 
  error: argument is of length zero
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Users/vnijs/Library/R/3.1/library/MSGFplus’
Error: Command failed (1)
In addition: Warning message:
Username parameter is deprecated. Please use thomasp85/MSGFplus

**Comment by adder** [comment]
Hi,

I got the same error on my linux machine. My java version is:
```
    java -version
    openjdk version "1.8.0_25"
    OpenJDK Runtime Environment (build 1.8.0_25-b18)
    OpenJDK 64-Bit Server VM (build 25.25-b02, mixed mode)
```
The error is:
```
* installing *source* package ‘MSGFplus’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error : .onLoad failed in loadNamespace() for 'MSGFplus', details:
  call: if (as.numeric(sub(".*\"\\d\\.(\\d).*", "\\1", javaVersion)) < 
  error: argument is of length zero
Error: loading failed
Execution halted
    ERROR: loading failed
```

Greetz

**Comment by thomasp85** [comment]
Hi Vincent

I just had time to look into your Radiant app. It is really impressive - especially the state saving and markdown support. I’ll probably steal those implementations for some of my future projects :-)

good job!

Thomas

**Comment by vnijs** [comment]
Thanks Thomas. The calling the report/markdown-creation functions is a bit messy. Hope to clean that up a bit. Suggestions welcome.

For saving state also take a look at https://github.com/jcheng5/shiny-resume/pull/1 This makes saving state easier when running on a server with multiple users. If you have any ideas on how to make this work well with and without renderUI let us know. It doesn't affect me all that much because I only have renderUI in radiant.

On a somewhat related note ... do you have any comments on [this question](http://stackoverflow.com/questions/28655735/avoiding-copies-by-using-environments) I posted a little while back? Hadley's comment is, I assume, a lot closer to your research area than it is to mine.

**Comment by thomasp85** [comment]
Vincent

Sorry for not getting back to you on your SO question - I’ve read through it and I’m afraid I’m not quite sure what the actual question is… How to best handle huge objects in R, or how to best use pass-by-reference semantics in R? If you clarify I’ll be happy to weigh in…

On a completely different note (and related to one of your comments in this thread) I’m working on a more general server-side framework for the occasions where Shiny’s model of coupling server and UI just feels too constrained. The package (Fiery) is only concerned with server-side logic, making it possible to do whatever on the front-end you may wish (including using a variety of front-end MVC frameworks such as Angular and Ember). It is in the very early stage at the moment, and is a pass time project, but I thought you may be interested…

/Thomas

**Comment by vnijs** [comment]
Thomas,




The question refers to a statement Hadley made in his book about how in your area packages apparantly use environments to pass around data. I assume that means that rather than pass an actual data.frame to functions a reference to that data is provided. I was just wondering if you know any examples that demonstrate how to set that up and, perhaps more importantly,  how to check that you are doing it correctly. I currently put data in my shiny app in a reactive value which is a special kind of list. I don't know if there is something like a reactive environment in Shiny. There might be. Rather than pass around data I pass a string with the dataset name. The data is then accessed by looking up the appropriate entry in the reactiveValues object (r_value in my app). Comments/suggestions welcome.




Fiery sounds interesting! Might be a challenge to 'compete' with the shiny framework though. There is also opencpu which does, I think, something similar that what you are thinking about. It does allow you to use Angular and others as a front end. Jeroen Ooms has a bunch of JavaScript stuff that may be of some relevance for you (e.g., js and V8). The htmlwidgets package also allows communication between R and js-libraries.




You may also be interested in Spyre. There are a few projects on github with that name so you would have to check which is the R based one. I seem to recall there was also a project that does something similar to Shiny but with a different type of reactive model. Can't remember the name but I know it is on github.




I am not an expert in server-side tech but I am not sure using R as the server is likely to produce a high performance system. What about a full-stack Java-script system (e.g., meteor) that calls R only for analysis as needed? 




I actually really like Shiny and wouldn't have been able to create radiant without it. My current knowledge of JavaScript is limited so easy access for a regular R user would be important. That said,  my main pain-points in Shiny are: 

1. Difficult to reuse code because inputs cannot be reused. This seems to be a javascript issue though.

2. Testing reactive functions and determining where an error occurs. Finding bugs in Python seemed much easier than in R in general however.

3. Shiny's environment is not easily accessible to package function in the R/ directory

4. Not designed to support package creation. This doesn't help with automated testing either since tools are setup to test code in R (mainly).




Vincent

**Comment by thomasp85** [comment]
Ok. I think I get the question now. Of course I can’t really speak for what Hadley were referring to but once upon a time this was more relevant than it is now. For an example you could have a look at xcms and the xcmsRaw class therein (it’s a bioconductor package). With that being set I don’t really see much point in replicating that behaviour anymore - while R uses pass-by-copy, it uses it in a smart way so that elements are only copied once they are modified. Passing around a large object in R is thus not a problem as long as you only read from it. The main selling point of environments instead of lists for huge datasets was because lists would make a complete deep copy every time an element was changed - quite a costly operation! Environments didn’t have this problem so they were more efficient for storing data that continuously needed to be modified. This all changed in R 3.1 (or somewhere around that version) where lists were changed so they avoided the deep copy of the whole list on element mutations…

Bottom line is that environments now are mostly useful if you want to program in a more C++/javascript/python kind of object oriented way, with reference passing and methods linked to objects instead of generics - this behaviour is implemented in refClasses and the R6 package for instance.

To sum up, I don’t think you need to worry so much about how you store your data within Shiny. Of course if you have really huge data, and want persistence then it should be put in a database, but otherwise just use lists or reactiveValues…

As for Fiery, I have no intentions of competing with Shiny - I even state it clearly that I believe Shiny would be the right choice in 99% of all use cases - I’ll look in to some of the packages you mentioned (those I don’t know already). Your concern for the suitability of R as a backend engine is valid, but in my case the infrastructure offered by Bioconductor is unparalleled within bioinformatics. For these types of applications (such as MSGFgui), where R is mostly used as a data store/analysis engine it makes good sense. But you’re right that whatever Fiery ends up being, it will probably never compete with Django or Ruby on Rails… (nor should it)

best

Thomas

**Comment by vnijs** [comment]
Thanks for the reference to xcms although it sounds like it may not be as influential as I thought. I'll focus on adding interaction with databases first.
